import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "react-hot-toast"
import { SessionProvider } from "next-auth/react"
import Navigation from "@/components/common/Navigation"

import { Inter as FontSans } from "next/font/google"

import { cn } from "@/lib/utils"

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
})

const inter = Inter({ subsets: ["latin"] })

export const revalidate = 0
export const dynamic = "force-dynamic"

export const metadata: Metadata = {
	title: "Virtual Seating CMS",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				<SessionProvider>
					<Navigation>{children}</Navigation>
				</SessionProvider>

				<Toaster />
			</body>
		</html>
	)
}
